import type { RoleCurriculum } from "./types";

export const PRODUCT_MARKETING_CURRICULUM: RoleCurriculum = {
  roleSlug: "product-marketing",
  title: "AI Product Marketing Roadmap",
  phases: [
    {
      id: "phase-1",
      title: "Phase 1 — Product Marketing Foundations",
      order: 1,
      moduleSlug: "pmm-foundations",
      moduleTitle: "Product Marketing Foundations",
      moduleDescription:
        "PMM role basics, ICP, positioning, GTM, and competitive analysis for AI products.",
      topics: [
        {
          id: "what-is-pmm",
          number: 1,
          title: "What is Product Marketing?",
          learn: [
            "Role of PMM",
            "Difference between PM vs PMM",
            "Product lifecycle",
            "User psychology",
            "Messaging",
          ],
          resources: [
            { label: "PMM overview (YouTube)", url: "https://www.youtube.com/watch?v=3nL1m9Qh5xQ", type: "video" },
            { label: "Product Marketing Alliance", url: "https://productmarketingalliance.com/", type: "article" },
            { label: "PM vs PMM (YouTube)", url: "https://www.youtube.com/watch?v=ui17kM3J6dM", type: "video" },
          ],
        },
        {
          id: "icp",
          number: 2,
          title: "Understanding ICP (Ideal Customer Profile)",
          learn: [
            "Customer segmentation",
            "User personas",
            "B2B vs B2C ICP",
            "Pain points",
            "Jobs-to-be-done",
          ],
          resources: [
            { label: "ICP fundamentals (YouTube)", url: "https://www.youtube.com/watch?v=sfGtw2C95Ms", type: "video" },
            { label: "Jobs-to-be-done framework", url: "https://www.intercom.com/blog/jobs-to-be-done-framework/", type: "article" },
            { label: "HubSpot persona builder", url: "https://www.hubspot.com/make-my-persona", type: "tool" },
          ],
        },
        {
          id: "positioning",
          number: 3,
          title: "Positioning & Messaging",
          learn: [
            "Product positioning",
            "Messaging frameworks",
            "Value propositions",
            "Competitive differentiation",
          ],
          resources: [
            { label: "Positioning (YouTube)", url: "https://www.youtube.com/watch?v=QK6v4p6xD4M", type: "video" },
            { label: "April Dunford 4Ps", url: "https://www.mironov.com/4ps/", type: "article" },
            { label: "PMA positioning guide", url: "https://www.productmarketingalliance.com/positioning-and-messaging/", type: "article" },
          ],
        },
        {
          id: "gtm",
          number: 4,
          title: "Go-To-Market (GTM) Strategy",
          learn: ["Product launches", "GTM frameworks", "Launch planning", "Channel selection"],
          resources: [
            { label: "GTM strategy (YouTube)", url: "https://www.youtube.com/watch?v=0e0j6Q0f8mQ", type: "video" },
            { label: "GTM glossary — ProductPlan", url: "https://www.productplan.com/glossary/go-to-market-strategy/", type: "article" },
            { label: "HubSpot GTM guide", url: "https://blog.hubspot.com/marketing/go-to-market-strategy", type: "article" },
          ],
        },
        {
          id: "market-research",
          number: 5,
          title: "Market Research & Competitive Analysis",
          learn: ["Competitor mapping", "SWOT analysis", "Market sizing", "Trend analysis"],
          resources: [
            { label: "Competitive analysis (YouTube)", url: "https://www.youtube.com/watch?v=9lO06Zxhu88", type: "video" },
            { label: "Similarweb blog", url: "https://www.similarweb.com/blog/", type: "article" },
            { label: "Semrush competitive analysis", url: "https://www.semrush.com/blog/competitive-analysis/", type: "article" },
          ],
        },
      ],
    },
    {
      id: "phase-2",
      title: "Phase 2 — Growth & Distribution",
      order: 2,
      moduleSlug: "growth-distribution",
      moduleTitle: "Growth & Distribution",
      moduleDescription: "Acquisition, PLG, copywriting, content marketing, and community-led growth.",
      topics: [
        {
          id: "user-acquisition",
          number: 6,
          title: "User Acquisition",
          learn: ["Organic acquisition", "Paid acquisition", "Referral loops", "Product-led growth"],
          resources: [
            { label: "User acquisition (YouTube)", url: "https://www.youtube.com/watch?v=9zJx5n1yR3U", type: "video" },
            { label: "Reforge blog", url: "https://www.reforge.com/blog", type: "article" },
            { label: "Growth Design", url: "https://growth.design/", type: "article" },
          ],
        },
        {
          id: "plg",
          number: 7,
          title: "Product-Led Growth (PLG)",
          learn: ["Freemium models", "Activation metrics", "User onboarding", "Expansion loops"],
          resources: [
            { label: "PLG overview (YouTube)", url: "https://www.youtube.com/watch?v=V6xM6bL5zYQ", type: "video" },
            { label: "OpenView Partners", url: "https://openviewpartners.com/blog/", type: "article" },
            { label: "ProductLed blog", url: "https://productled.com/blog/", type: "article" },
          ],
        },
        {
          id: "copywriting",
          number: 8,
          title: "Copywriting for PMM",
          learn: ["Landing page copy", "CTA writing", "Emotional triggers", "Feature communication"],
          resources: [
            { label: "Copywriting basics (YouTube)", url: "https://www.youtube.com/watch?v=mWNYE5yVOzk", type: "video" },
            { label: "Copyhackers", url: "https://copyhackers.com/blog/", type: "article" },
            { label: "SaaS copy (YouTube)", url: "https://www.youtube.com/watch?v=ZuPZWhz4w0g", type: "video" },
          ],
        },
        {
          id: "content-marketing",
          number: 9,
          title: "Content Marketing",
          learn: ["SEO content", "LinkedIn growth", "Educational content", "Distribution systems"],
          resources: [
            { label: "Content marketing (YouTube)", url: "https://www.youtube.com/watch?v=0WUVV4l5w8U", type: "video" },
            { label: "Ahrefs blog", url: "https://ahrefs.com/blog/", type: "article" },
            { label: "Neil Patel blog", url: "https://neilpatel.com/blog/", type: "article" },
          ],
        },
        {
          id: "community-growth",
          number: 10,
          title: "Community-Led Growth",
          learn: ["Community flywheels", "Engagement loops", "Creator ecosystems", "Evangelism"],
          resources: [
            { label: "Community growth (YouTube)", url: "https://www.youtube.com/watch?v=6a-KB7iA4zk", type: "video" },
            { label: "Common Room blog", url: "https://www.commonroom.io/blog/", type: "article" },
            { label: "CMX Hub", url: "https://www.cmxhub.com/blog/", type: "article" },
          ],
        },
      ],
    },
    {
      id: "phase-3",
      title: "Phase 3 — AI Product Marketing",
      order: 3,
      moduleSlug: "ai-pmm",
      moduleTitle: "AI Product Marketing",
      moduleDescription: "AI positioning, onboarding, virality, and launch strategy for AI-native products.",
      topics: [
        {
          id: "ai-positioning",
          number: 11,
          title: "AI Product Positioning",
          learn: [
            "Positioning AI products",
            "AI differentiation",
            "Trust & reliability messaging",
            "AI adoption friction",
          ],
          resources: [
            { label: "AI positioning (YouTube)", url: "https://www.youtube.com/watch?v=fmJangHf4Yc", type: "video" },
            { label: "OpenAI ChatGPT", url: "https://openai.com/index/chatgpt/", type: "article" },
            { label: "Anthropic news", url: "https://www.anthropic.com/news", type: "article" },
          ],
        },
        {
          id: "ai-onboarding",
          number: 12,
          title: "AI User Onboarding",
          learn: ["Prompt onboarding", "AI education UX", "Empty states", "First-value experience"],
          study: [
            { label: "ChatGPT", url: "https://chatgpt.com" },
            { label: "Perplexity", url: "https://www.perplexity.ai" },
            { label: "Cursor", url: "https://cursor.com" },
            { label: "Notion AI", url: "https://www.notion.so/product/ai" },
          ],
          resources: [
            { label: "Growth Design case studies", url: "https://growth.design/case-studies/", type: "article" },
            { label: "AI onboarding UX (YouTube)", url: "https://www.youtube.com/watch?v=wL5rW4V7q8Q", type: "video" },
          ],
        },
        {
          id: "ai-virality",
          number: 13,
          title: "AI Virality & Growth Loops",
          learn: ["AI sharing loops", "Viral UX", "Social proof", "AI-generated content loops"],
          resources: [
            { label: "Lenny's Newsletter", url: "https://www.lennysnewsletter.com/", type: "article" },
            { label: "Growth loops (YouTube)", url: "https://www.youtube.com/watch?v=2m1k6X5V8eY", type: "video" },
          ],
        },
        {
          id: "ai-launch",
          number: 14,
          title: "AI Launch Strategy",
          learn: ["Product Hunt launches", "Beta launches", "Waitlist strategy", "Influencer seeding"],
          resources: [
            { label: "Product Hunt", url: "https://www.producthunt.com/", type: "tool" },
            { label: "Launch strategy (YouTube)", url: "https://www.youtube.com/watch?v=QkM6S4FQx9Q", type: "video" },
            { label: "Indie Hackers", url: "https://www.indiehackers.com/", type: "article" },
          ],
        },
      ],
    },
    {
      id: "phase-4",
      title: "Phase 4 — Analytics & Metrics",
      order: 4,
      moduleSlug: "analytics-metrics",
      moduleTitle: "Analytics & Metrics",
      moduleDescription: "Marketing metrics, growth analytics, and experimentation for PMM.",
      topics: [
        {
          id: "marketing-metrics",
          number: 15,
          title: "Marketing Metrics",
          learn: ["CAC", "LTV", "Retention", "Conversion funnels", "Activation rate"],
          resources: [
            { label: "Marketing metrics (YouTube)", url: "https://www.youtube.com/watch?v=4Q6t0M4bJ4Q", type: "video" },
            { label: "Mixpanel blog", url: "https://mixpanel.com/blog/", type: "article" },
            { label: "Amplitude blog", url: "https://amplitude.com/blog", type: "article" },
          ],
        },
        {
          id: "growth-analytics",
          number: 16,
          title: "Growth Analytics",
          learn: ["Cohort analysis", "Funnel analysis", "Attribution", "Experimentation"],
          resources: [
            { label: "Growth analytics (YouTube)", url: "https://www.youtube.com/watch?v=9R6h5iQHHfY", type: "video" },
            { label: "Mode SQL tutorial", url: "https://mode.com/sql-tutorial/", type: "article" },
            { label: "Reforge blog", url: "https://www.reforge.com/blog", type: "article" },
          ],
        },
      ],
    },
    {
      id: "phase-5",
      title: "Phase 5 — Tools Stack",
      order: 5,
      moduleSlug: "pmm-tools",
      moduleTitle: "PMM Tools Stack",
      moduleDescription: "HubSpot, Mixpanel, GA4, Ahrefs, Semrush, Notion, and Figma for PMM workflows.",
      topics: [
        {
          id: "pmm-tools",
          number: 17,
          title: "PMM Tools",
          learn: ["HubSpot", "Mixpanel", "GA4", "Ahrefs", "Semrush", "Notion", "Figma"],
          resources: [
            { label: "HubSpot Academy", url: "https://academy.hubspot.com/", type: "tool" },
            { label: "Google Analytics", url: "https://analytics.google.com/", type: "tool" },
            { label: "PMM tools overview (YouTube)", url: "https://www.youtube.com/watch?v=9e5G6A1hYkE", type: "video" },
          ],
        },
      ],
    },
    {
      id: "phase-6",
      title: "Phase 6 — Portfolio Building",
      order: 6,
      moduleSlug: "pmm-portfolio",
      moduleTitle: "PMM Portfolio Projects",
      moduleDescription: "Build and publish AI PMM proof-of-work for LinkedIn and your portfolio site.",
      topics: [
        {
          id: "portfolio",
          number: 18,
          title: "PMM Portfolio Projects",
          build: [
            "AI product launch plan",
            "GTM strategy doc",
            "Product teardown",
            "Positioning analysis",
            "AI onboarding redesign",
            "Growth strategy deck",
          ],
          learn: ["Post all projects publicly on LinkedIn + portfolio website."],
          resources: [
            { label: "Behance", url: "https://www.behance.net/", type: "tool" },
            { label: "Notion templates", url: "https://www.notion.so/templates", type: "tool" },
            { label: "Gamma", url: "https://gamma.app/", type: "tool" },
          ],
        },
      ],
    },
    {
      id: "phase-7",
      title: "Phase 7 — Interview Preparation",
      order: 7,
      moduleSlug: "pmm-interview",
      moduleTitle: "PMM Interview Prep",
      moduleDescription: "Positioning, GTM, market sizing, storytelling, metrics, and AI adoption strategy.",
      topics: [
        {
          id: "interview",
          number: 19,
          title: "PMM Interview Topics",
          learn: [
            "Product positioning",
            "GTM strategy",
            "Market sizing",
            "Product storytelling",
            "Metrics",
            "AI adoption strategy",
          ],
          resources: [
            { label: "PMM interviews (YouTube)", url: "https://www.youtube.com/watch?v=l2Q8c7H4f1k", type: "video" },
            { label: "Exponent", url: "https://www.tryexponent.com/", type: "tool" },
            { label: "Lenny Rachitsky (YouTube)", url: "https://www.youtube.com/@LennyRachitsky", type: "video" },
          ],
        },
      ],
    },
  ],
  youtubeChannels: [
    { title: "Lenny's Podcast", url: "https://www.youtube.com/@LennysPodcast" },
    { title: "Product School", url: "https://www.youtube.com/@ProductSchool" },
    { title: "Exponent", url: "https://www.youtube.com/@tryexponent" },
    { title: "HubSpot", url: "https://www.youtube.com/@HubSpot" },
    { title: "Reforge", url: "https://www.reforge.com/blog" },
    { title: "Y Combinator", url: "https://www.youtube.com/@ycombinator" },
    { title: "Ahrefs", url: "https://www.youtube.com/@Ahrefs" },
    { title: "Neil Patel", url: "https://www.youtube.com/@neilpatel" },
  ],
  blogs: [
    { title: "Lenny's Newsletter", url: "https://www.lennysnewsletter.com/" },
    { title: "Reforge blog", url: "https://www.reforge.com/blog" },
    { title: "Product Marketing Alliance", url: "https://productmarketingalliance.com/" },
    { title: "Growth Design", url: "https://growth.design/" },
    { title: "Ahrefs blog", url: "https://ahrefs.com/blog/" },
    { title: "OpenView Partners", url: "https://openviewpartners.com/blog/" },
  ],
  careerStrategy: [
    "Build AI-focused PMM case studies",
    "Learn growth + positioning deeply",
    "Build public proof of work on LinkedIn",
    "Study successful AI launches",
    "Create teardown content consistently",
    "Become strong in storytelling + GTM thinking",
    "Learn AI product behavior patterns",
  ],
  hiringCompanies: [
    "OpenAI",
    "Anthropic",
    "Google",
    "Microsoft",
    "Notion",
    "Perplexity",
    "Cursor",
    "Figma",
    "Canva",
    "Atlassian",
    "Stripe",
    "Razorpay",
    "Zepto",
    "Swiggy",
  ],
};
